fizzbuzzの提出物です
hiromisugie/ruby-practices pull request #1
Opened 2021-12-11 19:12 UTC by hiromisugie

一度、fjordllcのリポジトリにプルリクをしてしまいました、失礼しました。
こちらご確認よろしくお願いいたします。

2021-12-15 02:48 UTC, u1tnk requested changes
要件は満たしていますが、冗長な表現が多いので、単純な課題のうちに修正してみましょう。

rubyは while/for等はほぼ使わず、each等のEnumerator https://docs.ruby-lang.org/ja/latest/class/Enumerator.html の機能を使って繰り返しを表現します。
この場合は以下のようにrangeで1から20を作ってeachを使うと良いでしょう

```
(1..20).each do |i|
  ....
end
```

また、ifを elsifで繋げて順番を工夫する事で、 `a % 5 != 0 ` 等の「でないとき」の条件を減らせますのでやってみてください。

また、コメントを詳しく書いていますね。自分でコードを書きやすくする補助として書くのは良いのですが、提出物からは「ソースコードから読みとれないもの」以外は消しましょう。ソースコードと同じ内容が書いてあると、ノイズになりますし、ソースコードを先に修正するので中身とズレてしまう事も多いので。

2021-12-15 20:15 UTC, hiromisugie commented
@u1tnk さん、レビューありがとうございます！
・eachを使った書き方に変更
・elsifを使い順番を工夫して条件を減らす
・自分のメモで入れていたコメントアウトは全て削除
上記について更新したファイルを再アップしましたのでご確認をお願いできますでしょうか。

また、
> rubyは while/for等はほぼ使わず、each等のEnumerator の機能を使って繰り返しを表現
→こちらについてもアドバイスありがとうございます。参考までにお聞きしたいのですが、rubyでwhile/for等をあまり使わないというのは何か理由があったりするのでしょうか？（次のプラクティスのカレンダーでも今のところwhileを使っており、これもeach等に変えるよう検討しようと思います）

2021-12-21 02:22 UTC, u1tnk commented
> rubyでwhile/for等をあまり使わないというのは何か理由があったりするのでしょうか？（次のプラクティスのカレンダーでも今のところwhileを使っており、これもeach等に変えるよう検討しようと思います）

理由は each/mapなどの Enumeratorのメソッド群の方がwhile/forより便利というところだけですが、ほぼ使う人が居ないので使うと「特別な意図があるのかな？」と思ってしまうので、なおさら使わないようになってます。

2021-12-21 02:22 UTC, u1tnk approved these changes

2022-03-17 19:41 UTC, merged